// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"nft_object/app/dao/internal"
)

// accountLockDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type accountLockDao struct {
	*internal.AccountLockDao
}

var (
	// AccountLock is globally public accessible object for table t_account_lock operations.
	AccountLock accountLockDao
)

func init() {
	AccountLock = accountLockDao{
		internal.NewAccountLockDao(),
	}
}

// Fill with you ideas below.
