// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"nft_object/app/dao/internal"
	"nft_object/app/model"

	"github.com/gogf/gf/database/gdb"
)

// adminApiDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type adminApiDao struct {
	*internal.AdminApiDao
}

var (
	// AdminApi is globally public accessible object for table t_auth_admin_api operations.
	// 对外对象
	AdminApi adminApiDao
)

func init() {
	AdminApi = adminApiDao{
		internal.NewAdminApiDao(),
	}
}

// 处理成Struct
func (m *adminApiDao) Strcut(res gdb.Record) (info *model.AdminApi, err error) {
	if err = res.Struct(&info); err != nil {
		return nil, err
	}
	return
}

// 处理成数组
func (d *adminApiDao) Strcuts(res gdb.Result) (list []*model.AdminApi, err error) {
	if err = res.Structs(&list); err != nil {
		return nil, err
	}
	return
}
