// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"nft_object/app/dao/internal"
)

// adminAccountDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type adminAccountDao struct {
	*internal.AdminAccountDao
}

var (
	// AdminAccount is globally public accessible object for table t_admin_account operations.
	AdminAccount adminAccountDao
)

func init() {
	AdminAccount = adminAccountDao{
		internal.NewAdminAccountDao(),
	}
}

// Fill with you ideas below.
