// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"nft_object/app/core"
	"nft_object/app/dao/internal"
	"nft_object/app/model"

	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/util/gconv"
)

// apiGroupDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type apiGroupDao struct {
	*internal.ApiGroupDao
}

var (
	// 对外对象
	ApiGroup apiGroupDao
)

func init() {
	ApiGroup = apiGroupDao{
		internal.NewApiGroupDao(),
	}
}

// Fill with you ideas below.
// 处理成Struct
func (m *apiGroupDao) Strcut(res gdb.Record) (info *model.ApiGroup, err error) {
	if err = res.Struct(&info); err != nil {
		return nil, err
	}
	return
}

// 处理成数组
func (d *apiGroupDao) Strcuts(res gdb.Result) (list []*model.ApiGroup, err error) {
	if err = res.Structs(&list); err != nil {
		return nil, err
	}
	return
}

// 分页查询
func (d *apiGroupDao) Pagenation(params map[string]interface{}) (core.PageReult, error) {
	// 分页信息
	res, err := core.BaseDao.PagenationCommon(core.GdbModel{
		M:       d.M,
		DB:      d.DB,
		Table:   d.Table,
		Columns: gconv.Map(model.ApiGroup{}),
	}, params)
	if err != nil {
		return res, err
	}
	return res, nil
}
