// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"nft_object/app/dao/internal"
)

// nftAlbumDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type nftAlbumDao struct {
	*internal.NftAlbumDao
}

var (
	// NftAlbum is globally public accessible object for table t_nft_album operations.
	NftAlbum nftAlbumDao
)

func init() {
	NftAlbum = nftAlbumDao{
		internal.NewNftAlbumDao(),
	}
}

// Fill with you ideas below.
