// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// AdminAccountDao is the manager for logic model data accessing and custom defined data operations functions management.
type AdminAccountDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      adminAccountColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB              // DB is the raw underlying database management object.
	Table  string              // Table is the underlying table name of the DAO.
}

// AdminAccountColumns defines and stores column names for table t_admin_account.
type adminAccountColumns struct {
	Id         string // ID
	AdminId    string // 原始的公告id
	Account    string // 账号
	Info       string // 账号信息
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
	Enabled    string // 状态描述, 1: 正常使用，0: 删除
}

// NewAdminAccountDao creates and returns a new DAO object for table data access.
func NewAdminAccountDao() *AdminAccountDao {
	columns := adminAccountColumns{
		Id:         "id",
		AdminId:    "admin_id",
		Account:    "account",
		Info:       "info",
		CreateTime: "create_time",
		UpdateTime: "update_time",
		Enabled:    "enabled",
	}
	return &AdminAccountDao{
		C:     columns,
		M:     g.DB("default").Model("t_admin_account").Safe(),
		DB:    g.DB("default"),
		Table: "t_admin_account",
	}
}
