// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// AdminRoleDao is the manager for logic model data accessing and custom defined data operations functions management.
type AdminRoleDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      adminRoleColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB           // DB is the raw underlying database management object.
	Table  string           // Table is the underlying table name of the DAO.
}

// AdminRoleColumns defines and stores column names for table t_auth_admin_role.
type adminRoleColumns struct {
	Id           string //
	AdminId      string //
	RoleId       string //
	RoleName     string //
	Enabled      string // ״̬
	CreateUser   string //
	CreateTime   string //
	ModifiedUser string //
	ModifiedTime string //
}

// NewAdminRoleDao creates and returns a new DAO object for table data access.
func NewAdminRoleDao() *AdminRoleDao {
	columns := adminRoleColumns{
		Id:           "id",
		AdminId:      "admin_id",
		RoleId:       "role_id",
		RoleName:     "role_name",
		Enabled:      "enabled",
		CreateUser:   "create_user",
		CreateTime:   "create_time",
		ModifiedUser: "modified_user",
		ModifiedTime: "modified_time",
	}
	return &AdminRoleDao{
		C:     columns,
		M:     g.DB("default").Model("t_auth_admin_role").Safe(),
		DB:    g.DB("default"),
		Table: "t_auth_admin_role",
	}
}
